name: Bug
description: Report a defect with clear steps, actual vs expected result, and evidence.
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        ### Default routing (applied automatically if repo automation is enabled)
        - Assignees: **lukeabbott**, **JosephRosalesGSI**
        - Project: **Orion**
        - Project Status: **Scoping**
        
        If the defaults are not applied automatically, please set them manually after creating the issue.

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Select the product/module area.
      options:
        - Smarttable
        - PDF Composer
        - VRU
        - Punch
        - Integrations
        - Other
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      options:
        - Urgent
        - High
        - Normal
        - Low
    validations:
      required: true

  - type: input
    id: sp
    attributes:
      label: SP
      description: Story points (if known). Leave empty if TBD.
      placeholder: "e.g., 1, 2, 3, 5, 8"
    validations:
      required: false

  - type: dropdown
    id: mvp
    attributes:
      label: MVP
      options:
        - MVP
        - Not MVP
        - TBD
    validations:
      required: true

  - type: input
    id: sprint
    attributes:
      label: Sprint
      description: Sprint name/number if known (otherwise leave empty).
      placeholder: "e.g., Sprint 24"
    validations:
      required: false

  - type: dropdown
    id: documentation
    attributes:
      label: Documentation
      options:
        - Required
        - Not required
        - TBD
    validations:
      required: true

  - type: input
    id: release
    attributes:
      label: Release
      description: Target release if known (otherwise leave empty).
      placeholder: "e.g., 1.9"
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken and in what context? Mention where it happens and where it works.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Product area + environment + version/build.
    validations:
      required: true

  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide numbered, minimal steps so anyone can reproduce.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: What happened (include exact values, errors, or screenshots if possible).
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What should have happened.
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does it happen?
      options:
        - Always
        - Often
        - Sometimes
        - Rarely
        - Unable to define
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - Critical (blocks core workflow)
        - High (major workflow impact / no workaround)
        - Medium (workaround exists)
        - Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Add screenshots/videos/logs/record links.
      placeholder: |
        - Video:
        - Screenshots:
        - Logs:
        - Record link / ID:
    validations:
      required: false
