name: Bug
description: Report a defect with clear steps, actual vs expected result, and evidence.
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken and in what context? Mention where it happens and where it works.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Product area + environment + version/build.
    validations:
      required: true

  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide numbered, minimal steps so anyone can reproduce.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: What happened (include exact values, errors, or screenshots if possible).
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What should have happened.
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does it happen?
      options:
        - Always
        - Often
        - Sometimes
        - Rarely
        - Unable to define
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - Critical (blocks core workflow)
        - High (major workflow impact / no workaround)
        - Medium (workaround exists)
        - Low (minor issue)
    validations:
      required: true
